---
# roles/mongodb/tasks/ssl.yml
# generate ssl/tls certificates for mongo cluster

#ca certificate

- name: generate ca passphrase
  set_fact:
    ca_password: "{{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits,punctuation') }}"
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

- name: generate ca key
  community.crypto.openssl_privatekey_pipe:
    passphrase: '{{ ca_password }}'
    cipher: auto
  register: ca_key
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

- name: generate ca csr
  community.crypto.openssl_csr_pipe:
    privatekey_content: '{{ ca_key.privatekey }}'
    privatekey_passphrase: '{{ ca_password }}'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ ca_common_name }}'
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

- name: generate ca crt
  community.crypto.x509_certificate_pipe:
    privatekey_content: '{{ ca_key.privatekey }}'
    privatekey_passphrase: '{{ ca_password }}'
    csr_content: '{{ ca_csr.csr }}'
    provider: selfsigned
  register: ca_crt
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

#server certitificate

- name: generate server key
  community.crypto.openssl_privatekey_pipe:
  register: server_key
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

- name: generate server csr
  community.crypto.openssl_csr_pipe:
    privatekey_content: '{{ server_key.privatekey }}'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ common_name }}'
    use_common_name_for_san: false
  register: server_csr
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

- name: generate server cert signed with ca cert
  community.crypto.x509_certificate_pipe:
    privatekey_content: '{{ server_key.privatekey }}'
    csr_content: '{{ server_csr.csr }}'
    ownca_content: '{{ ca_crt.certificate }}'
    ownca_privatekey_content: '{{ ca_key.privatekey }}'
    ownca_privatekey_passphrase: '{{ ca_password }}'
    provider: ownca
  register: server_crt
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

- name: generate mongo security keyFile
  set_fact:
    keyFile: "{{ lookup('password', '/dev/null length=1024 chars=ascii_letters') }}"
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"

 # move ceritificate files

- name: create directory for ssl files
  file:
    path: /etc/ssl/mongodb
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'
    
- name: copy ssl files to nodes
  copy:
    dest: '{{ item.dest }}'
    content: '{{ item.src }}'
    owner: mongodb
    group: mongodb
    mode: '0640'
  loop:
    - { src: '{{ ca_crt.certificate }}', dest: /etc/ssl/mongodb/mongodb-ca-crt.pem }
    - { src: '{{ server_crt.certificate }}', dest: /etc/ssl/mongodb/mongodb-server-crt.pem }
    - { src: '{{ server_key.privatekey }}', dest: /etc/ssl/mongodb/mongodb-server-key.pem }
    - { src: '{{ keyFile }}', dest: /etc/ssl/mongodb/keyFile }  
  no_log: true 

- name:  updating permissions for keyFile
  file:
    path: /etc/ssl/mongodb/keyFile
    mode: '0600'

- name: copy over pem file
  blockinfile:
    owner: mongodb
    group: mongodb
    mode: '0640'
    path: /etc/ssl/mongodb/mongodb-server-pem.pem
    create: yes
    block: |
      {{ server_key.privatekey }}
      {{ server_crt.certificate }}

- name: clear varibles
  set_fact:
    ca_crt: ''
    ca_csr: ''
    ca_key: ''
    server_crt: ''
    server_csr: ''
    server_key: ''
  run_once: true
  delegate_to: "{{ groups['mongodb'][0] }}"