- name: Configuring environment
  hosts: localhost
  connection: local
  vars_files:
      - group_vars/mongodb/vars
      - group_vars/mongodb/secret_vars
  
  vars:
    count: 3
       
  tasks:
  - name: creating mongodb cluster
    linode.cloud.instance:
      label: '{{ instance_prefix }}{{ item }}'
      api_token: '{{ token }}'
      type: '{{ type }}'
      region: '{{ region }}'
      image: '{{ image }}'
      root_pass: '{{ root_pass }}'
      authorized_keys: '{{ ssh_keys }}'
      private_ip: true
      tags: '{{ linode_tags }}'
      state: present
    register: linode
    with_sequence: count='{{count}}'

  - name: Get info about an instance by label
    linode.cloud.instance_info:
      api_token: '{{ token }}'
      label: '{{ instance_prefix }}{{ item }}'
    register: info
    with_sequence: count='{{count}}'

  # new
  - name: set facts
    set_fact:
      # hostnames
      mongo1_hostname: '{{ info.results.0.instance.label }}.{{ cluster_name }}'
      mongo2_hostname: '{{ info.results.1.instance.label }}.{{ cluster_name }}'
      mongo3_hostname: '{{ info.results.2.instance.label }}.{{ cluster_name }}'
      # public ips
      mongo1_ip1: '{{ info.results.0.instance.ipv4[0] }}'
      mongo2_ip1: '{{ info.results.1.instance.ipv4[0] }}'
      mongo3_ip1: '{{ info.results.2.instance.ipv4[0] }}'
      # private ips
      mongo1_priv1: '{{ info.results.0.instance.ipv4[1] }}'
      mongo2_priv1: '{{ info.results.1.instance.ipv4[1] }}'
      mongo3_priv1: '{{ info.results.2.instance.ipv4[1] }}'

  - name: update group_vars
    blockinfile:
      path: ./group_vars/mongodb/vars
      marker: "# {mark} INSTANCE VARS"
      block: |
        # hostnames 
        mongo1_hostname: {{ mongo1_hostname }}
        mongo2_hostname: {{ mongo2_hostname }}
        mongo3_hostname: {{ mongo3_hostname }}
        # public ips
        mongo1_ip1: {{ mongo1_ip1 }}
        mongo2_ip1: {{ mongo2_ip1 }}
        mongo3_ip1: {{ mongo3_ip1 }}
        # private ips
        mongo1_priv1: {{ mongo1_priv1 }}
        mongo2_priv1: {{ mongo2_priv1 }}
        mongo3_priv1: {{ mongo3_priv1 }}
      
  - name: test connectivity
    ping: '{{ item }}'
    with_items:
      - '{{ mongo1_ip1 }}'
      - '{{ mongo2_ip1 }}'
      - '{{ mongo3_ip1 }}'  

  - name: update inventory
    blockinfile:
      path: ./hosts
      marker: "# {mark} MONGODB LINODES"
      block: |
        [mongodb]
        {{ mongo1_ip1 }}
        {{ mongo2_ip1 }}
        {{ mongo3_ip1 }}

  - name: update in-memory inventory
    add_host:
      name: '{{ item }}'
      groups: mongodb
    with_items:
      - '{{ mongo1_ip1 }}'
      - '{{ mongo2_ip1 }}'
      - '{{ mongo3_ip1 }}'

  - name: wait for port 22 to become open
    wait_for:
      port: 22
      host: '{{ item }}'
      search_regex: OpenSSH
      delay: 10
    connection: local
    with_items:
      - '{{ mongo1_ip1 }}'
      - '{{ mongo2_ip1 }}'
      - '{{ mongo3_ip1 }}'
