---
# roles/post/tasks/creds.yml

- name: writing deployment credentials locally
  blockinfile:
    path: "/home/{{ sudo_username }}/.deployment-secrets.txt"
    create: yes
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    mode: 0644 
    block: |
      # mongodb users
      
      user: mongo-admin
      password: {{ mongo_admin_pass }}

      user: mongo-root
      password: {{ mongo_root_pass }}

      user: {{ sudo_username }}
      password: {{ sudo_username_pass }}

      # SSL ca password
      {{ ca_password }}
