---
name: mirror
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # changed from 1

      - name: set up ssh
        run: |
          mkdir -p $HOME/.ssh
          #echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_github_mirror_ed25519
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          chmod 700 ~/.ssh
          eval $(ssh-agent)
          ssh-add $HOME/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MIRROR_SSH_PRIV_KEY }}

      - name: push to public mirror
        run: |
          ls -la
          #git remote remove origin
          #LAST_COMMIT=$(git rev-list main | head -n 1)
          #git checkout $LAST_COMMIT
          #git checkout --orphan temp_branch
          #git commit -m "initial commit"
          #git rebase --onto temp_branch $START_COMMIT main
          ##git remote add mirror git@github.com:linode-solutions/mongodb-marketplace-occ.git
          ##git push -u mirror main##
          #git remote add mirror git@github.com:linode-solutions/mongodb-marketplace-occ.git
          ##git push --mirror git@github.com:linode-solutions/mongodb-marketplace-occ.git##
          ####
          rm -rf .github
          git remote remove origin
          git init
          git remote add mirror git@github.com:linode-solutions/mongodb-marketplace-occ.git
          git push mirror main

