---
name: mirror
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: push to public mirror
        run: |
          git push --mirror https://github.com/linode-solutions/mongodb-marketplace-occ.git

